### PR TITLE
fix: populate ingress private ip when disable-private-ingress is false

### LINKED ISSUE #553: LoadBalancer does not populate IP field when `disable-public-network` is set.
I have created a service of type `LoadBalancer`, with the annotation `load-balancer.hetzner.cloud/disable-public-network: "true"`. The load-balancer has a private IP address assigned on my cluster's network (`172.29.0.3`), and responds correctly on this address. But, the status does not contain the LB's IP address:

```yaml
  status:
    loadBalancer: {}
```

When I create a service without the annotation, the status is correctly updated:

```yaml
  status:
    loadBalancer:
      ingress:
      - ip: 167.235.<snip>
      - ip: 2a01:4f8:<snip>
```

I think even if public access is disabled, the external IP should still be populated with the service's private network address, so that servers on my HCloud network (but outside the k8s cluster) can extract the address they can reach the service on. Also, without the load-balancer IP address, `external-dns` fails to add a record for this load-balancer.

### PR DESCRIPTION
**Pull request by jooola**
Closes #553

Refactor getting the ingresses for a load-balancer for both get load-balancer and ensure load-balancer, into using a shared function. This ensures we are consistent between the 2 methods.

Release notes:
The load balancer ingress IPs are now populated with the private IPs, unless the `load-balancer.hetzner.cloud/disable-private-ingress` annotation is set to `true`. Please make sure that you configured the annotation according to your needs, for example if you are using `external-dns`.

### CODE REVIEW

**Comment by jooola** [comment]
image

**Review by apricote — APPROVED** [review]
Awesome!

**Comment by apricote** [comment]
Ah, this now always adds the private ip to the addresses if set. IIRC we discussed that we want to add it only when no public IPs are available.

**Review by apricote — CHANGES_REQUESTED** [review]
See above comment

**Comment by jooola** [comment]
In that case, I am not sure to fully understand why it should be different between `EnsureLoadBalancer` and `GetLoadBalancer`. According to the cloud provider interface, I understand that both should not be really different.

If we need this difference to prevent a breaking change, we might not respect the `load-balancer.hetzner.cloud/disable-public-network` and  `load-balancer.hetzner.cloud/disable-private-ingress` annotations.

I think I understood that external dns might break because we are referencing a private IP that will never be reachable from the outside, but in that case people would have to set `disable-private-ingress`.

I might be missing something though :)

**Comment by apricote** [comment]
We investigated the history of this today. Looking at #49 and #118 it was intended that we always add external+internal IPs the the Service Status. The annotation `load-balancer.hetzner.cloud/disable-private-ingress=true` was meant to help with setups where this causes issues.

So this PR fixes a bug and restores the intended behavior.

**Review by apricote — APPROVED** [review]

**Pull request merged**
