### PR TITLE
Merge syself robot-capability

### PR DESCRIPTION
**Pull request by nupplaphil**
Hi all,

I'm currently trying to combine hetzner cloud, hetzner bare metal and kubernetes with using https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner .

I'm not THAT experienced with Go yet, but I try to merge the latest fixes of the official hetzner repo with the bare-metal-feature of syself.

Still Draft, since the tests are working local, but I'm completely unsure how to REALLY test it .. I'll try using it with my environment ;-)

### CODE REVIEW

**Comment by apricote** [comment]
Hey @nupplaphil, thank you for opening this PR. We are internally preparing to merge the Robot support from Syself and have a plan for some e2e tests.

**Comment by nupplaphil** [comment]
that's good to hear!

So does it mean this PR isn't necessary? Do you know when you will release the Robot support? :)
I think this would be a good enabler using Hetzner root and cloud services together!

**Comment by nupplaphil** [comment]
So I'm closing it again :-)

*all thumbs up* to @apricote work :-)

**Comment by apricote** [comment]
Sorry for nor responding, I am currently porting the changes myself & making some adjustements and refactorings along the way to make the code a bit easier to understand (e.g. #532).

**Pull request closed without merging**
